"""
qdcore.flaskapp - Flask application composition and generation

Provides utilities to compose Flask applications with conditional
blueprint loading based on configuration. Inspects /repos/ for
available packages and integrates them based on conf settings.
"""

import os


class FlaskAppComposer:
    """
    Composes Flask application code with conditional blueprint loading.

    Inspects available packages and generates application code that
    conditionally loads blueprints based on configuration settings.
    """

    def __init__(self, site_root, conf=None):
        """
        Initialize the Flask app composer.

        Args:
            site_root: Path to the site root directory
            conf: QdConf instance (optional, for checking enabled services)
        """
        self.site_root = site_root
        self.conf = conf
        self.repos_path = os.path.join(site_root, 'repos')

    def compose_app(self, filename="app.py"):
        """
        Create the main Flask application file.

        Writes an app.py file to the site root with create_app() factory
        function. Conditionally includes blueprints based on configuration.

        Args:
            filename: Name of the app file (default: app.py)

        Returns:
            Path to the created app file
        """
        # TODO: Inspect repos_path to discover available packages
        # TODO: Read conf to determine which services are enabled
        # TODO: Generate dynamic imports based on discovered packages

        # Check which services are enabled
        qdcomments_enabled = self._is_service_enabled('qdcomments')
        qdimages_enabled = self._is_service_enabled('qdimages')
        qdflask_enabled = self._is_service_enabled('qdflask')

        app_content = self._generate_app_content(
            qdcomments_enabled=qdcomments_enabled,
            qdimages_enabled=qdimages_enabled,
            qdflask_enabled=qdflask_enabled,
        )

        app_path = os.path.join(self.site_root, filename)
        with open(app_path, 'w', encoding='utf-8') as f:
            f.write(app_content)

        return app_path

    def _is_service_enabled(self, service_name):
        """
        Check if a service is enabled in configuration.

        Args:
            service_name: Name of the service (e.g., 'qdcomments')

        Returns:
            True if service is enabled, False otherwise
        """
        if self.conf is None:
            return False

        try:
            return self.conf.get(f'{service_name}.service_enabled', False)
        except Exception:
            return False

    def _generate_app_content(self, qdcomments_enabled=False,
                               qdimages_enabled=False,
                               qdflask_enabled=False):
        """
        Generate the Flask application code.

        Args:
            qdcomments_enabled: Include qdcomments blueprint
            qdimages_enabled: Include qdimages blueprint
            qdflask_enabled: Include qdflask authentication

        Returns:
            String containing the app.py content
        """
        # Build imports section
        imports = '''"""
Flask application factory.

Auto-generated by qdcore.flaskapp. Edit configuration in conf/ to
enable or disable features.
"""

import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()
'''

        # Add conditional imports
        if qdflask_enabled:
            imports += '''
# Authentication
from qdflask import init_auth
'''

        if qdimages_enabled:
            imports += '''
# Image management
from qdimages import init_image_manager
'''

        if qdcomments_enabled:
            imports += '''
# Comments system
from qdcomments import init_comments
'''

        # Build create_app function
        create_app = '''

def create_app():
    """Application factory."""
    app = Flask(__name__)

    # Load configuration
    app.config['SECRET_KEY'] = os.environ.get('SECRET_KEY', 'dev-key-change-in-production')
    app.config['SQLALCHEMY_DATABASE_URI'] = os.environ.get('DATABASE_URL', 'sqlite:///app.db')
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    # Initialize extensions
    db.init_app(app)
'''

        # Add conditional initialization
        if qdflask_enabled:
            create_app += '''
    # Initialize authentication
    init_auth(app, db)
'''

        if qdimages_enabled:
            create_app += '''
    # Initialize image manager
    init_image_manager(app, db)
'''

        if qdcomments_enabled:
            create_app += '''
    # Initialize comments
    init_comments(app, db)
'''

        # Add basic route and return
        create_app += '''
    # Basic health check route
    @app.route('/health')
    def health():
        return {'status': 'ok'}

    return app


if __name__ == '__main__':
    application = create_app()
    application.run(debug=True)
'''

        return imports + create_app


def compose_app(site_root, conf=None, filename="app.py"):
    """
    Convenience function to compose a Flask application.

    Args:
        site_root: Path to the site root directory
        conf: QdConf instance (optional)
        filename: Name of the app file (default: app.py)

    Returns:
        Path to the created app file
    """
    composer = FlaskAppComposer(site_root, conf=conf)
    return composer.compose_app(filename=filename)
