#!python
"""
Generate reproducible site bootstrap files from a single source of truth.

qdbootstrap.py works with three files in a target directory:

  bootstrap.toml       - Single source of truth (input for generate,
                         output of save)
  qdboot.sh            - Generated shell script with plan and make modes
  qdboot_answers.toml  - Generated answer file passed to qdstart via -a

Commands:
  generate <target_dir>  - Read bootstrap.toml, write qdboot.sh and
                           qdboot_answers.toml
  save <target_dir> <site_dir> - Read a site's conf/, write bootstrap.toml
"""

import os
import sqlite3
import stat
import sys
import tomllib

if sys.version_info[0] < 3:
    print(f"Python 3 or greater required. Running {sys.version}.")
    sys.exit(-1)


THIS_MODULE_PATH = os.path.abspath(__file__)
# Navigate from qdutils/src/qdutils/qdbootstrap.py to quickdev root
QDUTILS_PKG_PATH = os.path.dirname(THIS_MODULE_PATH)  # qdutils/src/qdutils
QDUTILS_SRC_PATH = os.path.dirname(QDUTILS_PKG_PATH)  # qdutils/src
QDUTILS_PATH = os.path.dirname(QDUTILS_SRC_PATH)       # qdutils
QDDEV_PATH = os.path.dirname(QDUTILS_PATH)             # quickdev root
QDBASE_DIR_NAME = "qdbase"
QDBASE_PATH = os.path.join(QDDEV_PATH, QDBASE_DIR_NAME)
QDBASE_SRC_PATH = os.path.join(QDBASE_PATH, "src")

# pylint: disable=wrong-import-position
try:
    from qdbase import cliargs
except ModuleNotFoundError:
    sys.path.insert(0, QDBASE_SRC_PATH)
    from qdbase import cliargs

from qdbase import exenv
from qdbase import qdos
# pylint: enable=wrong-import-position


# Standardized file names
BOOTSTRAP_TOML = "bootstrap.toml"
BOOT_SCRIPT = "qdboot.sh"
BOOT_ANSWERS = "qdboot_answers.toml"

# Relative path from quickdev root to qdstart.py
QDSTART_REL_PATH = os.path.join(
    "qdutils", "src", "qdutils", "qdstart.py"
)


def _find_qdstart_path(repo_paths):
    """
    Find the qdstart.py path from the list of repo paths.

    Checks each repo for qdutils/src/qdutils/qdstart.py and returns
    the full path to the first match.

    Args:
        repo_paths: List of "mode::path" strings (e.g. "e::/path/to/repo")

    Returns:
        Absolute path to qdstart.py, or None if not found
    """
    for entry in repo_paths:
        # Strip mode prefix
        if "::" in entry:
            repo_path = entry.split("::", 1)[1]
        else:
            repo_path = entry
        candidate = os.path.join(repo_path, QDSTART_REL_PATH)
        if os.path.isfile(candidate):
            return candidate
    return None


def _build_shell_script(config, qdstart_path):
    """
    Build the contents of qdboot.sh from the bootstrap config.

    Args:
        config: Parsed bootstrap.toml dict
        qdstart_path: Absolute path to qdstart.py

    Returns:
        String containing the shell script
    """
    site_dpath = config["site"]["site_dpath"]
    python = config.get("site", {}).get("python", "python3")
    repo_paths = config.get("repos", {}).get("paths", [])
    cleanup_dirs = config.get("cleanup", {}).get("remove_dirs", [])

    # Build -r flags
    repo_flags = []
    for entry in repo_paths:
        repo_flags.append(f'\t-r {entry} \\')

    repo_flags_str = "\n".join(repo_flags)

    # Build cleanup commands
    cleanup_cmds = []
    for d in cleanup_dirs:
        cleanup_cmds.append(f"    rm -fr {d}")
    cleanup_str = "\n".join(cleanup_cmds)

    script = f"""#!/bin/sh
# Generated by qdbootstrap.py - do not edit directly.
# Edit bootstrap.toml and run: python qdbootstrap.py generate <dir>

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ACTION="${{1:?Usage: qdboot.sh plan|make}}"

case "$ACTION" in
  plan)
    EXTRA_ARGS="--plan"
    ;;
  make)
    EXTRA_ARGS=""
    deactivate 2>/dev/null
{cleanup_str}
    ;;
  *)
    echo "Usage: qdboot.sh plan|make" >&2
    exit 1
    ;;
esac

{python} {qdstart_path} \\
\t$EXTRA_ARGS \\
\t-s {site_dpath} \\
\t-a "$SCRIPT_DIR/{BOOT_ANSWERS}" \\
{repo_flags_str}
"""
    # Remove trailing backslash from last repo flag line
    lines = script.rstrip().rsplit("\n")
    if lines[-1].rstrip().endswith("\\"):
        lines[-1] = lines[-1].rstrip().rstrip("\\").rstrip()
    return "\n".join(lines) + "\n"


def _build_answers(config):
    """
    Extract [answers.*] sub-tables from config into a flat dict
    suitable for write_toml.

    [answers.qdimages] -> top-level [qdimages] in the answer file
    [answers.denv]     -> top-level [denv] in the answer file

    Args:
        config: Parsed bootstrap.toml dict

    Returns:
        Dict ready for qdos.write_toml()
    """
    answers = config.get("answers", {})
    result = {}
    for key, value in answers.items():
        if isinstance(value, dict):
            result[key] = dict(value)
        else:
            result[key] = value
    return result


def generate_bootstrap(target_dir, quiet=False, debug=0):
    """
    Read bootstrap.toml and generate qdboot.sh and qdboot_answers.toml.

    Args:
        target_dir: Directory containing bootstrap.toml
        quiet: Suppress informational output
        debug: Debug level
    """
    target_dir = os.path.abspath(target_dir)
    bootstrap_fpath = os.path.join(target_dir, BOOTSTRAP_TOML)

    if not os.path.isfile(bootstrap_fpath):
        print(f"Error: {bootstrap_fpath} not found.")
        sys.exit(1)

    with open(bootstrap_fpath, "rb") as f:
        config = tomllib.load(f)

    # Validate required fields
    if "site" not in config or "site_dpath" not in config["site"]:
        print("Error: bootstrap.toml must have [site] with site_dpath.")
        sys.exit(1)
    if "repos" not in config or "paths" not in config["repos"]:
        print("Error: bootstrap.toml must have [repos] with paths.")
        sys.exit(1)

    # Find qdstart.py
    repo_paths = config["repos"]["paths"]
    qdstart_path = _find_qdstart_path(repo_paths)
    if qdstart_path is None:
        print("Error: Could not find qdstart.py in any repo path.")
        print("  Expected at: <repo>/" + QDSTART_REL_PATH)
        sys.exit(1)

    # Write qdboot_answers.toml
    answers = _build_answers(config)
    answers_fpath = os.path.join(target_dir, BOOT_ANSWERS)
    _write_answers_toml(answers_fpath, answers)
    if not quiet:
        print(f"Wrote {answers_fpath}")

    # Write qdboot.sh
    script = _build_shell_script(config, qdstart_path)
    script_fpath = os.path.join(target_dir, BOOT_SCRIPT)
    with open(script_fpath, "w", encoding="utf-8") as f:
        f.write(script)
    # Set executable
    st = os.stat(script_fpath)
    os.chmod(script_fpath, st.st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    if not quiet:
        print(f"Wrote {script_fpath}")


def _write_answers_toml(filepath, data):
    """
    Write the answers TOML file with a header comment.

    Args:
        filepath: Output file path
        data: Dict of answer tables
    """
    lines = [
        "# Generated by qdbootstrap.py - do not edit directly.",
        "# Edit bootstrap.toml and run: python qdbootstrap.py generate <dir>",
        "",
    ]
    # Use qdos.write_toml logic but prepend our header
    body_lines = []
    qdos._write_toml_table(body_lines, data, [])
    lines.extend(body_lines)

    with open(filepath, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
        if lines:
            f.write("\n")


def save_bootstrap(target_dir, site_dir, quiet=False, debug=0):
    """
    Read a site's configuration and write bootstrap.toml.

    Args:
        target_dir: Directory to write bootstrap.toml into
        site_dir: Existing site directory with conf/
        quiet: Suppress informational output
        debug: Debug level
    """
    target_dir = os.path.abspath(target_dir)
    site_dir = os.path.abspath(site_dir)
    conf_dir = os.path.join(site_dir, "conf")

    if not os.path.isdir(conf_dir):
        print(f"Error: No conf/ directory found at {conf_dir}")
        sys.exit(1)

    os.makedirs(target_dir, exist_ok=True)

    # (1) Read repos.db
    repos_db_fpath = os.path.join(conf_dir, "repos.db")
    repo_paths = []
    if os.path.isfile(repos_db_fpath):
        conn = sqlite3.connect(repos_db_fpath)
        try:
            cursor = conn.execute(
                "SELECT path, editable FROM repositories ORDER BY id"
            )
            for path, editable in cursor.fetchall():
                prefix = "e::" if editable else "p::"
                repo_paths.append(f"{prefix}{path}")
        finally:
            conn.close()

    # (2) Read site.toml for site_dpath
    site_toml_fpath = os.path.join(conf_dir, "site.toml")
    site_dpath = site_dir  # default
    if os.path.isfile(site_toml_fpath):
        with open(site_toml_fpath, "rb") as f:
            site_toml = tomllib.load(f)
        # site.toml stores qdsite_dpath at top level
        if "qdsite_dpath" in site_toml:
            stored = site_toml["qdsite_dpath"]
            # If stored value is relative (like "blog"), resolve to absolute
            if not os.path.isabs(stored):
                site_dpath = site_dir
            else:
                site_dpath = stored

    # (3) Read all conf/*.toml files (excluding site.toml) -> [answers.<name>]
    answers = {}
    for fname in sorted(os.listdir(conf_dir)):
        if fname == "site.toml":
            continue
        if fname.endswith(".toml"):
            fpath = os.path.join(conf_dir, fname)
            with open(fpath, "rb") as f:
                data = tomllib.load(f)
            section_name = fname[:-5]  # strip .toml
            if data:
                answers[section_name] = data

    # (4) Read .env -> [answers.denv]
    env_fpath = os.path.join(conf_dir, ".env")
    if os.path.isfile(env_fpath):
        env_vars = {}
        with open(env_fpath, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                if "=" in line:
                    key, value = line.split("=", 1)
                    value = value.strip().strip('"').strip("'")
                    env_vars[key.strip()] = value
        if env_vars:
            answers["denv"] = env_vars

    # (5) Build cleanup with site_dpath as default
    cleanup_dirs = [site_dpath]

    # (6) Assemble bootstrap.toml
    bootstrap = {
        "site": {
            "site_dpath": site_dpath,
            "python": "python3",
        },
        "repos": {
            "paths": repo_paths,
        },
        "cleanup": {
            "remove_dirs": cleanup_dirs,
        },
        "answers": answers,
    }

    # Write with header comments
    bootstrap_fpath = os.path.join(target_dir, BOOTSTRAP_TOML)
    _write_bootstrap_toml(bootstrap_fpath, bootstrap)
    if not quiet:
        print(f"Wrote {bootstrap_fpath}")


def _write_bootstrap_toml(filepath, data):
    """
    Write bootstrap.toml with descriptive header comments.

    Args:
        filepath: Output file path
        data: Bootstrap config dict
    """
    header = [
        "# QuickDev Bootstrap Configuration",
        "#",
        "# Single source of truth for reproducible site creation.",
        "# Edit this file, then run:  python qdbootstrap.py generate <dir>",
        "# To capture an existing site: python qdbootstrap.py save <dir> <site>",
        "",
    ]
    body_lines = []
    qdos._write_toml_table(body_lines, data, [])

    with open(filepath, "w", encoding="utf-8") as f:
        f.write("\n".join(header + body_lines))
        f.write("\n")


def main():
    """Main entry point for qdbootstrap CLI."""
    menu = cliargs.CliCommandLine()
    exenv.command_line_quiet(menu)
    exenv.command_line_debug(menu)
    exenv.command_line_site(menu)
    menu.add_item(cliargs.CliCommandLineParameterItem(
        "t", help_description="Target directory.",
        default_none=True, value_type=cliargs.PARAMETER_STRING
    ))

    # generate action
    m = menu.add_item(
        cliargs.CliCommandLineActionItem(
            "generate",
            generate_bootstrap,
            help_description="Generate qdboot.sh and qdboot_answers.toml "
                             "from bootstrap.toml.",
        )
    )
    m.add_parameter(
        cliargs.CliCommandLineParameterItem(
            exenv.ARG_Q_QUIET, parameter_name="quiet", is_positional=False
        )
    )
    m.add_parameter(
        cliargs.CliCommandLineParameterItem(
            exenv.ARG_D_DEBUG, parameter_name="debug", is_positional=False
        )
    )
    m.add_parameter(
        cliargs.CliCommandLineParameterItem(
            "t", parameter_name="target_dir", is_positional=False,
            is_required=True, value_type=cliargs.PARAMETER_STRING
        )
    )

    # save action
    m = menu.add_item(
        cliargs.CliCommandLineActionItem(
            "save",
            save_bootstrap,
            help_description="Save site configuration to bootstrap.toml.",
        )
    )
    m.add_parameter(
        cliargs.CliCommandLineParameterItem(
            exenv.ARG_Q_QUIET, parameter_name="quiet", is_positional=False
        )
    )
    m.add_parameter(
        cliargs.CliCommandLineParameterItem(
            exenv.ARG_D_DEBUG, parameter_name="debug", is_positional=False
        )
    )
    m.add_parameter(
        cliargs.CliCommandLineParameterItem(
            "t", parameter_name="target_dir", is_positional=False,
            is_required=True, value_type=cliargs.PARAMETER_STRING
        )
    )
    m.add_parameter(
        cliargs.CliCommandLineParameterItem(
            exenv.ARG_S_SITE_DPATH, parameter_name="site_dir",
            is_positional=False, is_required=True,
            value_type=cliargs.PARAMETER_STRING
        )
    )

    menu.cli_run()


if __name__ == "__main__":
    main()
